import { useEffect, useState } from "react";
import { useAuth } from "../../context/AuthContext";
import { createBusinessClaim, getBusinessClaims, getPlaces } from "../../services/api";
import DashboardShell from "./DashboardShell";
import "./dashboard.css";
export default function ClaimPage(){const {token}=useAuth();const [query,setQuery]=useState("");const [places,setPlaces]=useState([]);const [claims,setClaims]=useState([]);const [message,setMessage]=useState("");const [error,setError]=useState("");
 function loadClaims(){getBusinessClaims(token).then(setClaims).catch(e=>setError(e.message))}useEffect(loadClaims,[token]);
 async function search(e){e.preventDefault();try{setError("");setPlaces(await getPlaces({search:query}))}catch(err){setError(err.message)}}
 async function claim(place){try{await createBusinessClaim(token,{place_id:place.id,verification_method:"manual",verification_note:"Requested from the owner dashboard."});setMessage(`Claim submitted for ${place.name}.`);loadClaims()}catch(err){setError(err.message)}}
 return <DashboardShell><div className="dashboard-heading"><div><p className="dashboard-eyebrow">CLAIM BUSINESS</p><h1>Connect an existing listing</h1><p>Find your business in our current directory and submit a claim.</p></div></div><section className="dashboard-panel"><form className="claim-search" onSubmit={search}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by business name" minLength="2" required/><button className="dashboard-primary">Search</button></form>{message&&<div className="dashboard-alert success">{message}</div>}{error&&<div className="dashboard-alert error">{error}</div>}<div className="claim-results">{places.slice(0,8).map(place=><article key={place.id}><div><h3>{place.name}</h3><p>{place.full_address||place.city||"Address unavailable"}</p></div><button onClick={()=>claim(place)}>Claim</button></article>)}</div></section><section className="dashboard-panel claims-panel"><h2>Your claims</h2>{claims.length===0?<p>No claims submitted.</p>:claims.map(claim=><div className="claim-row" key={claim.id}><span><strong>{claim.business_name}</strong><small>Submitted {new Date(claim.created_at).toLocaleDateString()}</small></span><b className={`claim-status ${claim.status}`}>{claim.status}</b></div>)}</section></DashboardShell>}
